name: Build on several platforms

on:
  workflow_dispatch:
  pull_request:
  release:
    types: [created]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            file_extension: linux
          - os: macos-11
            file_extension: macos
          - os: windows-2019
            file_extension: windows.exe

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: '3.10'

      - name: Create environment and build
        run: pdm install && pdm bundle

      - name: Test
        run: ./dist/ipython-with-capytaine-${{ matrix.file_extension }} --help

      - name: Upload built files
      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        if: github.event_name == 'release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/ipython-with-capytaine-${{ matrix.file_extension }}
          asset_name: ipython-with-capytaine-${{ matrix.file_extension }}
          asset_content_type: application/octet-stream
