name: Build on several platforms

on:
  workflow_dispatch:
  pull_request:
  release:
    types: [created]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11, windows-2019]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: '3.10'

      - name: Create environment and build
        run: pdm install && pdm bundle

      - name: Test
        run: ./dist/ipython-with-capytaine-* --help

      - name: Upload build file
        uses: actions/upload-artifact@v3
        with:
          path: ./dist/*

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        if: github.event_name == 'release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/ipython-with-capytaine-*
          asset_name: Executable
          asset_content_type: application/octet-stream
