name: Build on several platforms

on:
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11, windows-2019]

    steps:
      - uses: actions/checkout@v3

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: '3.10'

      - run: pdm bundle

      - run: ./dist/ipython-with-capytaine --help

      # - uses: actions/upload-artifact@v3
      #   with:
      #     path: ./dist/
